import AppBar from "@/components/AppBar";
import "./globals.css";
import { dir } from "i18next";
import Providers from "@/components/Providers";

const language = "fa";

export const metadata = {
  title: "Next-Auth Tutorial",
  description: "Generated by Sakura Dev",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang={language} dir={dir(language)}>
      <body>
        <Providers>
          <AppBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}


